### ISSUE TITLE
OffsetY is not working? 

### ISSUE THREAD

**Issue by JustBarnt** [svelte-plugins/tooltips#4]
I can move the tooltip on the X access by going `use:tooltip={{style: offsetX: "50px"}}` but replacing `offsetX` with `offsetY` it does not move at all. Am I missing something?

**Comment by JustBarnt** [comment]
Update it doesn't even move creating a custom theme

```javascript
<span use:tooltip={{ theme: "custom-tooltip", style: toolTipStyles, content: "This field supports wild card search (%, _, [], [^])", animation: "fade", position: "right" }}> Customer:</span>
```

```css
:global(.tooltip.custom-tooltip){
		--tooltip-offset-y: -50rem;
	}
```
